/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cotrust_myapplication_MainActivity */

#ifndef _Included_com_cotrust_myapplication_MainActivity
#define _Included_com_cotrust_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cotrust_myapplication_MainActivity
 * Method:    getAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cotrust_myapplication_MainActivity_getAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cotrust_myapplication_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cotrust_myapplication_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
